<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Admin-PC" name="com.cgg.testcases.TransferOfLicenceOfficerProcess" tests="5" failures="0" timestamp="10 Jan 2017 09:48:05 GMT" time="0.003" errors="5">
  <testcase name="getTheAppToProcessGrantOfLicence" time="0.003" classname="com.cgg.testcases.TransferOfLicenceOfficerProcess">
    <error type="java.io.FileNotFoundException" message="D:\Rashi_Workspace\TsFactories\src\com\cgg\config\config.properties (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: D:\Rashi_Workspace\TsFactories\src\com\cgg\config\config.properties (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.cgg.testcases.TestBase.initialize(TestBase.java:65)
	at com.cgg.testcases.TestBase.beforetest(TestBase.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- getTheAppToProcessGrantOfLicence -->
  <testcase name="putTheStatusAsQuery" time="0.000" classname="com.cgg.testcases.TransferOfLicenceOfficerProcess">
    <error type="java.lang.Throwable" message="Method TransferOfLicenceOfficerProcess.putTheStatusAsQuery()[pri:0, instance:com.cgg.testcases.TransferOfLicenceOfficerProcess@3c0ecd4b] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TransferOfLicenceOfficerProcess.putTheStatusAsQuery()[pri:0, instance:com.cgg.testcases.TransferOfLicenceOfficerProcess@3c0ecd4b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- putTheStatusAsQuery -->
  <testcase name="ReplyTOQueryByTheEntreprenuer" time="0.000" classname="com.cgg.testcases.TransferOfLicenceOfficerProcess">
    <error type="java.lang.Throwable" message="Method TransferOfLicenceOfficerProcess.ReplyTOQueryByTheEntreprenuer()[pri:2, instance:com.cgg.testcases.TransferOfLicenceOfficerProcess@3c0ecd4b] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TransferOfLicenceOfficerProcess.ReplyTOQueryByTheEntreprenuer()[pri:2, instance:com.cgg.testcases.TransferOfLicenceOfficerProcess@3c0ecd4b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- ReplyTOQueryByTheEntreprenuer -->
  <testcase name="putTheStatusAsScrutinyCompleted" time="0.000" classname="com.cgg.testcases.TransferOfLicenceOfficerProcess">
    <error type="java.lang.Throwable" message="Method TransferOfLicenceOfficerProcess.putTheStatusAsScrutinyCompleted()[pri:0, instance:com.cgg.testcases.TransferOfLicenceOfficerProcess@3c0ecd4b] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TransferOfLicenceOfficerProcess.putTheStatusAsScrutinyCompleted()[pri:0, instance:com.cgg.testcases.TransferOfLicenceOfficerProcess@3c0ecd4b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- putTheStatusAsScrutinyCompleted -->
  <testcase name="putTheStatusAsRejected" time="0.000" classname="com.cgg.testcases.TransferOfLicenceOfficerProcess">
    <error type="java.lang.Throwable" message="Method TransferOfLicenceOfficerProcess.putTheStatusAsRejected()[pri:4, instance:com.cgg.testcases.TransferOfLicenceOfficerProcess@3c0ecd4b] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TransferOfLicenceOfficerProcess.putTheStatusAsRejected()[pri:4, instance:com.cgg.testcases.TransferOfLicenceOfficerProcess@3c0ecd4b] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- putTheStatusAsRejected -->
</testsuite> <!-- com.cgg.testcases.TransferOfLicenceOfficerProcess -->
